In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv(
    "../data/processed/global_superstore_clean.csv",
    parse_dates=["order_date", "ship_date"]
)

In [3]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [8]:
username = "postgres"
password = "casty123"
host = "localhost"
port = "5432"
database = "retail_analytics"

In [9]:
engine = create_engine(
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

In [10]:
with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!

In [12]:
from sqlalchemy import text

with open("../sql/create_tables.sql", "r") as file:
    sql = file.read()

with engine.begin() as conn:
    conn.execute(text(sql))

print("✅ orders table created successfully.")

✅ orders table created successfully.

In [13]:
df.to_sql(
    "orders",
    con=engine,
    if_exists="append",
    index=False
)

print("✅ Data loaded successfully.")

✅ Data loaded successfully.

In [14]:
query = """
SELECT COUNT(*) AS total_records
FROM orders;
"""

pd.read_sql(query, engine)

   total_records
0          51290